### ISSUE TITLE
SDB Viewer crashed when I tried to access the Settings section.

### ISSUE THREAD

**Issue by sargoon** [mathisdt/sdbviewer#7]
Expected behavior

The users should be able to access Settings section on the SDB Viewer Application.

Actual behavior

When I tried to click on settings in SDB Viewer, the application gave an error and crashed immediately.

How to reproduce

- Open the SDB Viewer app.
- Then click on the Settings.
- And you will see that the application crashes immediately.

- App version: 1.3
- Operating system: Android 5.1.1

Recording Of The Bug

https://youtu.be/XrhcCcT4x3w

**Comment by mathisdt** [comment]
Hi @sargoon, thanks for the bug report! The problem you described (and documented) did and does neither occur in my emulator nor on my physical devices, but I think I found the problem from the logs you sent me via the "oops" dialog.

**Comment by mathisdt** [comment]
I just published v1.4. Please report if the problem persists.

**Comment by sargoon** [comment]
You're welcome! I could not see the new version of your app on the F-Droid.
